### ISSUE TITLE
Add support multiple ETH accounts

### ISSUE THREAD

**Issue by Azazel020** [Aerilym/session-node-bot#1]
I can't currently monitor the nodes within 1 account that I host for third parties, which means I have to deal with multiple ETH addresses.

In the current version it is only possible to specify 1 ETH address, it would be an addition to be able to specify multiple addresses here.

**Comment by Aerilym** [comment]
Thanks for the report, you should be able to use the `address` command to do this. Try `/help address` to learn more about the command and its usage examples. You can add multiple addresses using `/address add ...`. Let me know if this works.

**Comment by Azazel020** [comment]
It works, I can add multiple addresses. When I run the command /address list I see now 2 addresses but it doesn’t show the alias.
