### ISSUE TITLE
Node list after adding ETH-address

### ISSUE THREAD

**Issue by Marky-N** [Aerilym/session-node-bot#7]
Hi,
Tried out the bot and it really looks great so far!

I added my ETH-address with /address add XXXXXXXXX
The list I got started "Nodes operated", giving the two nodes I'm operating. Next set, also started with "Nodes operated", although it should actually be "Staked nodes", with the list of nodes staked.

Here you find the physical example.
<img width="323" alt="Screenshot 2024-11-15 at 12 03 01" src="https://github.com/user-attachments/assets/6fd3267d-6919-4747-9bd9-c48473de9b7b">

**Comment by Aerilym** [comment]
Thanks for flagging this, I've pushed a fix and updated the bot
